Update to match trunk/master changes

diff --git a/LZ4/config/cmake/binex/example/test.sh.in b/LZ4/config/cmake/binex/example/test.sh.in
--- a/LZ4/config/cmake/binex/example/test.sh.in
+++ b/LZ4/config/cmake/binex/example/test.sh.in
@@ -43,11 +43,32 @@ AWK='awk'
 ENVCMD="env HDF5_PLUGIN_PATH=`pwd`/../src/.libs"
 
 TESTDIR=$builddir
+PLUGIN_LIBDIR=plugins
+FROM_DIR=`pwd`/../src/.libs
+PLUGIN_LIB="$FROM_DIR/libh5lz4.so.*"
+
+# Create test directories if not exists yet.
+test -d $PLUGIN_LIBDIR || mkdir -p $PLUGIN_LIBDIR
+if [ $? != 0 ]; then
+    echo "Failed to create test directory($PLUGIN_LIBDIR)"
+    exit $EXIT_FAILURE
+fi
+
+# copy plugin library for test
+$CP $PLUGIN_LIB $PLUGIN_LIBDIR
+if [ $? != 0 ]; then
+    echo "Failed to copy plugin library ($PLUGIN_LIB) for test."
+    exit $EXIT_FAILURE
+fi
+
+# setup plugin path
+ENVCMD="env HDF5_PLUGIN_PATH=${PLUGIN_LIBDIR}"
+
 SRC_TESTFILES="$srcdir/testfiles"
 LIST_TEST_FILES="
 $SRC_TESTFILES/h5repack_layout.h5
-$SRC_TESTFILES/h5ex_d_bzip2.ddl
-$SRC_TESTFILES/h5ex_d_bzip2.tst
+$SRC_TESTFILES/h5ex_d_lz4.ddl
+$SRC_TESTFILES/h5ex_d_lz4.tst
 $SRC_TESTFILES/h5repack_layout.h5-ud_convert.ddl
 $SRC_TESTFILES/ud_convert.h5repack_layout.h5.tst
 "
@@ -76,7 +97,7 @@ COPY_TESTFILES_TO_TESTDIR()
                 $CP -f $tstfile $TESTDIR
                 if [ $? -ne 0 ]; then
                     echo "Error: FAILED to copy $tstfile ."
-                
+
                     # Comment out this to CREATE expected file
                     exit $EXIT_FAILURE
                 fi
@@ -169,13 +190,13 @@ DUMPTEST() {
     cat $actual_err >> $actual
 
     CMP_OUTPUT $expect $actual
-    
+
     # Clean up output file
 #    rm -f $actual $actual_err
 
 }
 
-REPACKTEST() 
+REPACKTEST()
 {
     infile=$1
     outfile=$2
@@ -193,7 +214,7 @@ REPACKTEST()
     RET=$?
     STDOUT_FILTER $actual
     cat $actual_err >> $actual
-    
+
      if [ $RET != 0 ] ; then
         echo "*FAILED*"
         nerrors="`expr $nerrors + 1`"
@@ -213,7 +234,7 @@ EXETEST() {
     actual_err="`basename $2 .tst`.err1"
 
     # Run test.
-    TESTING $fname 
+    TESTING $fname
     (
       $ENVCMD ./$fname
     ) >$actual 2>$actual_err
@@ -229,11 +250,11 @@ EXETEST() {
 
 COPY_TESTFILES_TO_TESTDIR
 
-EXETEST h5ex_d_bzip2 h5ex_d_bzip2.tst
+EXETEST h5ex_d_lz4 h5ex_d_lz4.tst
 
-DUMPTEST h5ex_d_bzip2.ddl h5ex_d_bzip2.h5
+DUMPTEST h5ex_d_lz4.ddl h5ex_d_lz4.h5
 
-REPACKTEST h5repack_layout.h5 out-ud_convert.h5repack_layout.h5 -v -f UD=307,1,9
+REPACKTEST h5repack_layout.h5 out-ud_convert.h5repack_layout.h5 -v -f UD=307,1,9 -l CHUNK=4x5
 
 DUMPTEST h5repack_layout.h5-ud_convert.ddl -pH out-ud_convert.h5repack_layout.h5
 
