Merge changes w.r.t. blosc files

diff --git a/LZF/example/test.sh.in b/LZF/example/test.sh.in
--- a/LZF/example/test.sh.in
+++ b/LZF/example/test.sh.in
@@ -40,9 +40,28 @@ DIRNAME='dirname'
 LS='ls'
 AWK='awk'
 
-ENVCMD="env HDF5_PLUGIN_PATH=`pwd`/../src/.libs"
-
 TESTDIR=$builddir
+PLUGIN_LIBDIR=plugins
+FROM_DIR=`pwd`/../src/.libs
+PLUGIN_LIB="$FROM_DIR/libh5lzf.so.*"
+
+# Create test directories if not exists yet.
+test -d $PLUGIN_LIBDIR || mkdir -p $PLUGIN_LIBDIR
+if [ $? != 0 ]; then
+    echo "Failed to create test directory($PLUGIN_LIBDIR)"
+    exit $EXIT_FAILURE
+fi
+
+# copy plugin library for test
+$CP $PLUGIN_LIB $PLUGIN_LIBDIR
+if [ $? != 0 ]; then
+    echo "Failed to copy plugin library ($PLUGIN_LIB) for test."
+    exit $EXIT_FAILURE
+fi
+
+# setup plugin path
+ENVCMD="env HDF5_PLUGIN_PATH=${PLUGIN_LIBDIR}"
+
 SRC_TESTFILES="$srcdir/testfiles"
 LIST_TEST_FILES="
 $SRC_TESTFILES/h5repack_layout.h5
@@ -215,7 +234,7 @@ EXETEST() {
     # Run test.
     TESTING $fname
     (
-      $ENVCMD ./$fname
+      $ENVCMD `pwd`/$fname
     ) >$actual 2>$actual_err
     cat $actual_err >> $actual
 
@@ -226,6 +245,8 @@ EXETEST() {
 ################################
 #########  THE TESTS   #########
 ################################
+
+echo $ENVCMD
 
 COPY_TESTFILES_TO_TESTDIR
 
